import { useState } from 'react';
import { ArrowUp, ArrowDown, Check, ExternalLink, Plus, Save, Trash2 } from 'lucide-react';
import { makeMealDraft, moduleLink, planDay, previewMeal, type DayPlan, type MealDraft, type WorkspaceRecord, type WorkspaceSnapshot } from '../ai/local/familyWorkspace';
import type { SaveWorkspace } from './WorkspaceMemory';

const field = 'app-field mt-1 min-h-10 w-full rounded-lg px-2 py-2';
export function WorkspacePlans({ snapshot, records, save, available }: { snapshot: WorkspaceSnapshot; records: WorkspaceRecord[]; save: SaveWorkspace; available: boolean }) {
  const [mode, setMode] = useState<'meal' | 'day'>('meal');
  const [meal, setMeal] = useState<MealDraft>();
  const [day, setDay] = useState<DayPlan>({ date: snapshot.range.start, from: '08:00', until: '18:00', travelMinutes: 15, steps: [] });
  const [result, setResult] = useState<ReturnType<typeof planDay>>();
  const [existing, setExisting] = useState<WorkspaceRecord>();
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState('');
  const mealPreview = meal ? previewMeal(snapshot, meal) : undefined;
  const current = mode === 'meal' ? meal : day;
  const updateDay = (next: DayPlan) => { setDay(next); setResult(undefined); };
  const savePlan = async () => {
    if (!current || busy) return;
    setBusy(true);
    try {
      const title = mode === 'meal' ? `${mealPreview?.recipe?.title || 'Repas'} · ${meal?.date}` : `Journée du ${day.date}`;
      const saved = await save(mode, title.slice(0, 100), existing?.audience || 'personal', current, existing);
      if (saved) { setNotice('Préparation enregistrée. Retrouvez-la dans la liste des préparations.'); setExisting(saved); }
    } finally { setBusy(false); }
  };
  return <section aria-label="Préparations reliées" className="space-y-5">
    <div role="tablist" aria-label="Type de préparation" className="flex gap-2 border-b border-family-border">{([['meal', 'Repas et courses'], ['day', 'Organisation de journée']] as const).map(([id, label]) => <button key={id} role="tab" aria-selected={mode === id} className={`min-h-11 border-b-2 px-2 text-sm ${mode === id ? 'border-family-primary font-bold' : 'border-transparent'}`} onClick={() => { setMode(id); setExisting(undefined); setNotice(''); }}>{label}</button>)}</div>
    <label className="block text-sm">Préparations enregistrées<select aria-label="Préparation enregistrée" className={field} value={existing?.id || ''} onChange={event => { const record = records.find(item => item.id === event.target.value); setExisting(record); if (!record) return; if (record.kind === 'meal') setMeal(structuredClone(record.payload as MealDraft)); else { setDay(structuredClone(record.payload as DayPlan)); setResult(undefined); } setNotice('Recalculez avec les données actuelles avant de poursuivre.'); }}><option value="">Nouvelle préparation</option>{records.filter(record => record.kind === mode).map(record => <option key={record.id} value={record.id}>{record.title}</option>)}</select></label>
    {mode === 'meal' && <div className="space-y-4">
      <label className="block text-sm">Recette familiale<select aria-label="Recette à préparer" className={field} value={meal?.recipeId || ''} onChange={event => { const recipe = snapshot.recipes.find(item => item.id === event.target.value); setMeal(recipe ? makeMealDraft(recipe, meal?.date || snapshot.range.start, meal?.servings || recipe.servings || 4) : undefined); setExisting(undefined); }}><option value="">Choisir une recette</option>{snapshot.recipes.map(recipe => <option key={recipe.id} value={recipe.id}>{recipe.title}</option>)}</select></label>
      {!snapshot.recipes.length && <p className="text-sm text-family-text-secondary">Aucune recette chargée. Enregistrez une recette dans votre carnet pour la préparer ici.</p>}
      {meal && <><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><label className="text-sm">Date<input aria-label="Date du repas" className={field} type="date" value={meal.date} onChange={event => setMeal({ ...meal, date: event.target.value })} /></label><label className="text-sm">Portions souhaitées<input aria-label="Portions souhaitées" className={field} type="number" min="1" max="100" value={meal.servings} onChange={event => setMeal({ ...meal, servings: Number(event.target.value) })} /></label><label className="text-sm">Recette prévue pour<input aria-label="Portions de référence" className={field} type="number" min="1" max="100" value={meal.baseServings || ''} onChange={event => setMeal({ ...meal, baseServings: Number(event.target.value) })} /></label></div>
        <h3 className="font-bold">Ingrédients de référence</h3>
        <ul className="space-y-3">{meal.ingredients.map((item, index) => <li key={index} className="grid grid-cols-[minmax(0,1fr)_5rem_6rem] gap-2"><label className="min-w-0 text-xs">Ingrédient<input aria-label={`Ingrédient ${index + 1}`} className={field} maxLength={80} value={item.name} onChange={event => setMeal({ ...meal, ingredients: meal.ingredients.map((row, i) => i === index ? { ...row, name: event.target.value } : row) })} /></label><label className="text-xs">Quantité<input aria-label={`Quantité ${index + 1}`} className={field} type="number" min="0.001" step="any" value={item.quantity ?? ''} onChange={event => setMeal({ ...meal, ingredients: meal.ingredients.map((row, i) => i === index ? { ...row, quantity: event.target.value ? Number(event.target.value) : null, resolved: Boolean(event.target.value) } : row) })} /></label><label className="text-xs">Unité<input aria-label={`Unité ${index + 1}`} className={field} maxLength={20} value={item.unit} onChange={event => setMeal({ ...meal, ingredients: meal.ingredients.map((row, i) => i === index ? { ...row, unit: event.target.value } : row) })} /></label></li>)}</ul>
        <div className="border-l-2 border-family-primary pl-3" aria-live="polite"><h3 className="font-bold">Conséquences pour {meal.servings} personnes</h3><ul className="mt-2 space-y-2 text-sm">{mealPreview?.lines.map((item, i) => <li key={i}>{item.text}{item.existing.length > 0 && <p className="text-xs text-family-warning">Déjà référencé : {item.existing.map(row => `${row.quantity || 'quantité inconnue'}${row.inStock ? ' en stock déclaré' : row.checked ? ' acheté' : ' sur la liste'}`).join(', ')}. À vérifier avant ajout.</p>}</li>)}</ul></div>
        {mealPreview?.warnings.map(warning => <p key={warning} role="status" className="text-sm text-family-warning">{warning}</p>)}
        <p className="text-xs text-family-text-secondary">La recette, la date et les portions restent liées dans cette préparation. La liste de courses et les stocks du foyer ne sont pas modifiés.</p>
        <a href={moduleLink('courses')} className="flex min-h-10 items-center gap-2 text-sm text-family-primary"><ExternalLink size={16} />Ouvrir le carnet et les courses</a>
      </>}
    </div>}
    {mode === 'day' && <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><label className="text-sm">Jour<input aria-label="Jour à organiser" className={field} type="date" value={day.date} onChange={event => updateDay({ ...day, date: event.target.value })} /></label><label className="text-sm">Début<input aria-label="Début de journée" className={field} type="time" value={day.from} onChange={event => updateDay({ ...day, from: event.target.value })} /></label><label className="text-sm">Retour avant<input aria-label="Retour avant" className={field} type="time" value={day.until} onChange={event => updateDay({ ...day, until: event.target.value })} /></label><label className="text-sm">Trajet / marge (min)<input aria-label="Marge de déplacement" className={field} type="number" min="0" max="180" value={day.travelMinutes} onChange={event => updateDay({ ...day, travelMinutes: Number(event.target.value) })} /></label></div>
      {snapshot.events.filter(event => event.date === day.date && !event.duration && !event.allDay).map(event => <label key={event.id} className="block text-sm">Durée estimée de « {event.title} » (min)<input aria-label={`Durée de ${event.title}`} className={field} type="number" min="5" max="720" value={day.durationEstimates?.[event.id] || ''} onChange={change => { const estimates = { ...day.durationEstimates }; if (change.target.value) estimates[event.id] = Number(change.target.value); else delete estimates[event.id]; updateDay({ ...day, durationEstimates: estimates }); }} /></label>)}
      <ol className="divide-y divide-family-border">{day.steps.map((step, index) => <li key={step.id} className="space-y-2 py-3"><div className="flex gap-2"><input aria-label={`Étape ${index + 1}`} className="app-field min-w-0 flex-1 rounded-lg p-2 text-sm" maxLength={100} value={step.title} onChange={event => updateDay({ ...day, steps: day.steps.map(row => row.id === step.id ? { ...row, title: event.target.value } : row) })} /><button title="Supprimer l’étape" aria-label={`Supprimer étape ${index + 1}`} onClick={() => updateDay({ ...day, steps: day.steps.filter(row => row.id !== step.id) })} className="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-family-border"><Trash2 size={16} /></button></div><div className="grid grid-cols-2 gap-2"><label className="text-xs">Durée (min)<input aria-label={`Durée étape ${index + 1}`} className={field} type="number" min="5" max="720" value={step.duration} onChange={event => updateDay({ ...day, steps: day.steps.map(row => row.id === step.id ? { ...row, duration: Number(event.target.value) } : row) })} /></label><label className="text-xs">Après un rendez-vous<select aria-label={`Après rendez-vous étape ${index + 1}`} className={field} value={step.afterEventId || ''} onChange={event => updateDay({ ...day, steps: day.steps.map(row => row.id === step.id ? { ...row, afterEventId: event.target.value || undefined } : row) })}><option value="">Aucun</option>{snapshot.events.filter(event => event.date === day.date).map(event => <option key={event.id} value={event.id}>{event.title}</option>)}</select></label></div><div className="flex flex-wrap items-center gap-3">{snapshot.members.map(member => <label key={member.id} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={step.memberIds.includes(member.id)} onChange={event => updateDay({ ...day, steps: day.steps.map(row => row.id === step.id ? { ...row, memberIds: event.target.checked ? [...row.memberIds, member.id] : row.memberIds.filter(id => id !== member.id) } : row) })} />{member.name}</label>)}{([-1, 1] as const).map(direction => <button key={direction} aria-label={`${direction < 0 ? 'Monter' : 'Descendre'} étape ${index + 1}`} title={direction < 0 ? 'Monter' : 'Descendre'} disabled={index + direction < 0 || index + direction >= day.steps.length} onClick={() => { const steps = [...day.steps]; [steps[index], steps[index + direction]] = [steps[index + direction], steps[index]]; updateDay({ ...day, steps }); }} className="grid h-9 w-9 place-items-center rounded-lg border border-family-border disabled:opacity-30">{direction < 0 ? <ArrowUp size={15} /> : <ArrowDown size={15} />}</button>)}</div></li>)}</ol>
      <button disabled={day.steps.length >= 8} onClick={() => updateDay({ ...day, steps: [...day.steps, { id: crypto.randomUUID(), title: '', duration: 30, memberIds: [snapshot.actorId] }] })} className="flex min-h-10 items-center gap-2 text-sm text-family-primary"><Plus size={16} />Ajouter une étape</button>
      <button disabled={!day.steps.length || day.steps.some(step => !step.title.trim())} onClick={() => setResult(planDay(snapshot, day))} className="flex min-h-11 items-center gap-2 rounded-lg border border-family-border px-3 text-sm disabled:opacity-40"><Check size={16} />Comparer les déroulés</button>
      {result && <div aria-live="polite" className="space-y-3">{result.warnings.map(warning => <p key={warning} className="text-sm text-family-warning">{warning}</p>)}{result.alternatives.map(alternative => <div key={alternative.label} className="border-l-2 border-family-primary pl-3"><h3 className="font-bold">{alternative.label}</h3><ol className="mt-2 space-y-2 text-sm">{alternative.steps.map(step => <li key={step.id}>{step.start} – {step.end} · {step.title}</li>)}</ol></div>)}{result.references.length > 0 && <p className="text-xs text-family-text-secondary">Rendez-vous pris en compte : {result.references.map(reference => reference.label).join(' ; ')}</p>}<p className="text-xs text-family-text-secondary">Les marges et durées complétées sont vos estimations. Aucun trajet réel ni disponibilité extérieure n’est calculé. Un rappel lié à un rendez-vous devra être revérifié si vous le déplacez.</p><a href={moduleLink('agenda')} className="flex min-h-10 items-center gap-2 text-sm text-family-primary"><ExternalLink size={16} />Ouvrir l’agenda</a></div>}
    </div>}
    {current && <button disabled={!available || busy || mode === 'meal' && !mealPreview?.ready || mode === 'day' && !result?.alternatives.length} onClick={savePlan} className="flex min-h-11 items-center gap-2 rounded-lg border border-family-border px-3 text-sm disabled:opacity-40"><Save size={16} />Enregistrer la préparation</button>}
    {notice && <p role="status" className="text-sm text-family-success">{notice}</p>}
  </section>;
}
