import { useState } from 'react';
import { Pencil, Save, Trash2 } from 'lucide-react';
import { validMemory, type ChosenMemory, type WorkspaceRecord, type WorkspaceSnapshot } from '../ai/local/familyWorkspace';

export type SaveWorkspace = (kind: WorkspaceRecord['kind'], title: string, audience: WorkspaceRecord['audience'], payload: WorkspaceRecord['payload'], existing?: WorkspaceRecord) => Promise<WorkspaceRecord | false>;
export function WorkspaceMemory({ snapshot, records, save, remove, available }: { snapshot: WorkspaceSnapshot; records: WorkspaceRecord[]; save: SaveWorkspace; remove(record: WorkspaceRecord): Promise<void>; available: boolean }) {
  const [draft, setDraft] = useState<ChosenMemory>({ trigger: '', meaning: '', kind: 'preference' });
  const [audience, setAudience] = useState<'personal' | 'family'>('personal');
  const [existing, setExisting] = useState<WorkspaceRecord>();
  const [consent, setConsent] = useState(false);
  const [busy, setBusy] = useState(false);
  const editable = (record: WorkspaceRecord) => record.owner_member_id === snapshot.actorId || record.audience === 'family' && snapshot.parent;
  const update = (next: ChosenMemory) => { setDraft(next); setConsent(false); };
  return <section aria-label="Mémoire choisie" className="space-y-5">
    <h2 className="font-bold">Ce que l’assistant retient</h2>
    <form className="space-y-3" onSubmit={async event => { event.preventDefault(); if (!consent || !validMemory(draft) || busy) return; setBusy(true); try { if (await save('memory', draft.trigger, audience, draft, existing)) { setExisting(undefined); setDraft({ trigger: '', meaning: '', kind: 'preference' }); setConsent(false); } } finally { setBusy(false); } }}>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Type<select aria-label="Type de mémoire" value={draft.kind} onChange={event => update({ ...draft, kind: event.target.value as ChosenMemory['kind'] })} className="app-field mt-1 w-full rounded-lg p-2"><option value="preference">Préférence</option><option value="shortcut">Phrase raccourcie</option></select></label><label className="text-sm">Visible par<select aria-label="Visibilité de la mémoire" value={audience} onChange={event => { setAudience(event.target.value as 'personal' | 'family'); setConsent(false); }} className="app-field mt-1 w-full rounded-lg p-2" disabled={Boolean(existing && existing.owner_member_id !== snapshot.actorId)}><option value="personal">Moi uniquement</option>{snapshot.parent && <option value="family">Toute la famille</option>}</select></label></div>
      <label className="block text-sm">Nom ou phrase exacte<input aria-label="Phrase à retenir" value={draft.trigger} maxLength={80} onChange={event => update({ ...draft, trigger: event.target.value })} className="app-field mt-1 w-full rounded-lg p-2" /></label>
      <label className="block text-sm">{draft.kind === 'shortcut' ? 'Demande correspondante' : 'Préférence choisie'}<textarea aria-label="Signification de la mémoire" value={draft.meaning} maxLength={500} onChange={event => update({ ...draft, meaning: event.target.value })} className="app-field mt-1 w-full rounded-lg p-2" /></label>
      <label className="flex gap-2 text-xs"><input type="checkbox" checked={consent} onChange={event => setConsent(event.target.checked)} />Je souhaite conserver cette information entre mes appareils{audience === 'family' ? ' et la partager avec mon foyer' : ''}.</label>
      <div className="flex gap-3"><button disabled={!available || !consent || !validMemory(draft) || busy} className="flex min-h-11 items-center gap-2 rounded-lg border border-family-border px-3 text-sm disabled:opacity-40"><Save size={16} />{existing ? 'Enregistrer la modification' : 'Mémoriser'}</button>{existing && <button type="button" onClick={() => { setExisting(undefined); setDraft({ trigger: '', meaning: '', kind: 'preference' }); setAudience('personal'); setConsent(false); }} className="text-sm">Annuler</button>}</div>
    </form>
    <ul className="divide-y divide-family-border">{records.filter(record => record.kind === 'memory').map(record => <li key={record.id} className="flex items-start gap-2 py-4"><div className="min-w-0 flex-1"><p className="break-words text-sm font-bold">{record.title}</p><p className="mt-1 break-words text-sm">{(record.payload as ChosenMemory).meaning}</p><p className="mt-1 text-xs text-family-text-secondary">{record.audience === 'family' ? 'Famille' : 'Personnel'} · {new Date(record.updated_at).toLocaleDateString('fr-FR')}</p></div>{editable(record) && <><button title={`Modifier ${record.title}`} aria-label={`Modifier ${record.title}`} onClick={() => { setDraft({ ...record.payload as ChosenMemory }); setExisting(record); setAudience(record.audience); setConsent(false); }} className="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-family-border"><Pencil size={16} /></button><button title={`Oublier ${record.title}`} aria-label={`Oublier ${record.title}`} onClick={() => { if (window.confirm(`Oublier « ${record.title} » sur les appareils synchronisés ?`)) void remove(record); }} className="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-family-border"><Trash2 size={16} /></button></>}</li>)}</ul>
  </section>;
}
